spring:
  application:
    name: restaurant-pos

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_pos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: cretostudio115@gmail.com
    password: opia hell omqh lauy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-token-expiration: 900000       
    refresh-token-expiration: 604800000   

  otp:
    length: 6
    expiration-minutes: 5
    max-attempts: 5
    rate-limit-window-minutes: 30

  mail:
    from: cretostudio115@gmail.com
    from-name: Restaurant POS
